sudo: required
services:
  - docker

before_install:
  - docker build -t vaishali1256/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vaishali1256/docker-react npm run test